// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: bus.proto

package com.net.msg;

public final class BUS_MSG {
  private BUS_MSG() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface GTB_REGIST_ONLINEOrBuilder extends
      // @@protoc_insertion_point(interface_extends:GTB_REGIST_ONLINE)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int64 uid = 1;</code>
     */
    long getUid();

    /**
     * <code>int64 playerId = 2;</code>
     */
    long getPlayerId();

    /**
     * <code>string gate = 3;</code>
     */
    java.lang.String getGate();
    /**
     * <code>string gate = 3;</code>
     */
    com.google.protobuf.ByteString
        getGateBytes();

    /**
     * <code>string game = 4;</code>
     */
    java.lang.String getGame();
    /**
     * <code>string game = 4;</code>
     */
    com.google.protobuf.ByteString
        getGameBytes();
  }
  /**
   * Protobuf type {@code GTB_REGIST_ONLINE}
   */
  public  static final class GTB_REGIST_ONLINE extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:GTB_REGIST_ONLINE)
      GTB_REGIST_ONLINEOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use GTB_REGIST_ONLINE.newBuilder() to construct.
    private GTB_REGIST_ONLINE(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private GTB_REGIST_ONLINE() {
      uid_ = 0L;
      playerId_ = 0L;
      gate_ = "";
      game_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private GTB_REGIST_ONLINE(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              uid_ = input.readInt64();
              break;
            }
            case 16: {

              playerId_ = input.readInt64();
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              gate_ = s;
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              game_ = s;
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.net.msg.BUS_MSG.internal_static_GTB_REGIST_ONLINE_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.net.msg.BUS_MSG.internal_static_GTB_REGIST_ONLINE_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.net.msg.BUS_MSG.GTB_REGIST_ONLINE.class, com.net.msg.BUS_MSG.GTB_REGIST_ONLINE.Builder.class);
    }

    public static final int UID_FIELD_NUMBER = 1;
    private long uid_;
    /**
     * <code>int64 uid = 1;</code>
     */
    public long getUid() {
      return uid_;
    }

    public static final int PLAYERID_FIELD_NUMBER = 2;
    private long playerId_;
    /**
     * <code>int64 playerId = 2;</code>
     */
    public long getPlayerId() {
      return playerId_;
    }

    public static final int GATE_FIELD_NUMBER = 3;
    private volatile java.lang.Object gate_;
    /**
     * <code>string gate = 3;</code>
     */
    public java.lang.String getGate() {
      java.lang.Object ref = gate_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        gate_ = s;
        return s;
      }
    }
    /**
     * <code>string gate = 3;</code>
     */
    public com.google.protobuf.ByteString
        getGateBytes() {
      java.lang.Object ref = gate_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        gate_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int GAME_FIELD_NUMBER = 4;
    private volatile java.lang.Object game_;
    /**
     * <code>string game = 4;</code>
     */
    public java.lang.String getGame() {
      java.lang.Object ref = game_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        game_ = s;
        return s;
      }
    }
    /**
     * <code>string game = 4;</code>
     */
    public com.google.protobuf.ByteString
        getGameBytes() {
      java.lang.Object ref = game_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        game_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (uid_ != 0L) {
        output.writeInt64(1, uid_);
      }
      if (playerId_ != 0L) {
        output.writeInt64(2, playerId_);
      }
      if (!getGateBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, gate_);
      }
      if (!getGameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, game_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (uid_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, uid_);
      }
      if (playerId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, playerId_);
      }
      if (!getGateBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, gate_);
      }
      if (!getGameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, game_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.net.msg.BUS_MSG.GTB_REGIST_ONLINE)) {
        return super.equals(obj);
      }
      com.net.msg.BUS_MSG.GTB_REGIST_ONLINE other = (com.net.msg.BUS_MSG.GTB_REGIST_ONLINE) obj;

      boolean result = true;
      result = result && (getUid()
          == other.getUid());
      result = result && (getPlayerId()
          == other.getPlayerId());
      result = result && getGate()
          .equals(other.getGate());
      result = result && getGame()
          .equals(other.getGame());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + UID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getUid());
      hash = (37 * hash) + PLAYERID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getPlayerId());
      hash = (37 * hash) + GATE_FIELD_NUMBER;
      hash = (53 * hash) + getGate().hashCode();
      hash = (37 * hash) + GAME_FIELD_NUMBER;
      hash = (53 * hash) + getGame().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.net.msg.BUS_MSG.GTB_REGIST_ONLINE parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.net.msg.BUS_MSG.GTB_REGIST_ONLINE parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.net.msg.BUS_MSG.GTB_REGIST_ONLINE parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.net.msg.BUS_MSG.GTB_REGIST_ONLINE parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.net.msg.BUS_MSG.GTB_REGIST_ONLINE parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.net.msg.BUS_MSG.GTB_REGIST_ONLINE parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.net.msg.BUS_MSG.GTB_REGIST_ONLINE parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.net.msg.BUS_MSG.GTB_REGIST_ONLINE parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.net.msg.BUS_MSG.GTB_REGIST_ONLINE parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.net.msg.BUS_MSG.GTB_REGIST_ONLINE parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.net.msg.BUS_MSG.GTB_REGIST_ONLINE parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.net.msg.BUS_MSG.GTB_REGIST_ONLINE parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.net.msg.BUS_MSG.GTB_REGIST_ONLINE prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code GTB_REGIST_ONLINE}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:GTB_REGIST_ONLINE)
        com.net.msg.BUS_MSG.GTB_REGIST_ONLINEOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.net.msg.BUS_MSG.internal_static_GTB_REGIST_ONLINE_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.net.msg.BUS_MSG.internal_static_GTB_REGIST_ONLINE_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.net.msg.BUS_MSG.GTB_REGIST_ONLINE.class, com.net.msg.BUS_MSG.GTB_REGIST_ONLINE.Builder.class);
      }

      // Construct using com.net.msg.BUS_MSG.GTB_REGIST_ONLINE.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        uid_ = 0L;

        playerId_ = 0L;

        gate_ = "";

        game_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.net.msg.BUS_MSG.internal_static_GTB_REGIST_ONLINE_descriptor;
      }

      @java.lang.Override
      public com.net.msg.BUS_MSG.GTB_REGIST_ONLINE getDefaultInstanceForType() {
        return com.net.msg.BUS_MSG.GTB_REGIST_ONLINE.getDefaultInstance();
      }

      @java.lang.Override
      public com.net.msg.BUS_MSG.GTB_REGIST_ONLINE build() {
        com.net.msg.BUS_MSG.GTB_REGIST_ONLINE result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.net.msg.BUS_MSG.GTB_REGIST_ONLINE buildPartial() {
        com.net.msg.BUS_MSG.GTB_REGIST_ONLINE result = new com.net.msg.BUS_MSG.GTB_REGIST_ONLINE(this);
        result.uid_ = uid_;
        result.playerId_ = playerId_;
        result.gate_ = gate_;
        result.game_ = game_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.net.msg.BUS_MSG.GTB_REGIST_ONLINE) {
          return mergeFrom((com.net.msg.BUS_MSG.GTB_REGIST_ONLINE)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.net.msg.BUS_MSG.GTB_REGIST_ONLINE other) {
        if (other == com.net.msg.BUS_MSG.GTB_REGIST_ONLINE.getDefaultInstance()) return this;
        if (other.getUid() != 0L) {
          setUid(other.getUid());
        }
        if (other.getPlayerId() != 0L) {
          setPlayerId(other.getPlayerId());
        }
        if (!other.getGate().isEmpty()) {
          gate_ = other.gate_;
          onChanged();
        }
        if (!other.getGame().isEmpty()) {
          game_ = other.game_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.net.msg.BUS_MSG.GTB_REGIST_ONLINE parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.net.msg.BUS_MSG.GTB_REGIST_ONLINE) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long uid_ ;
      /**
       * <code>int64 uid = 1;</code>
       */
      public long getUid() {
        return uid_;
      }
      /**
       * <code>int64 uid = 1;</code>
       */
      public Builder setUid(long value) {
        
        uid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 uid = 1;</code>
       */
      public Builder clearUid() {
        
        uid_ = 0L;
        onChanged();
        return this;
      }

      private long playerId_ ;
      /**
       * <code>int64 playerId = 2;</code>
       */
      public long getPlayerId() {
        return playerId_;
      }
      /**
       * <code>int64 playerId = 2;</code>
       */
      public Builder setPlayerId(long value) {
        
        playerId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 playerId = 2;</code>
       */
      public Builder clearPlayerId() {
        
        playerId_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object gate_ = "";
      /**
       * <code>string gate = 3;</code>
       */
      public java.lang.String getGate() {
        java.lang.Object ref = gate_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          gate_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string gate = 3;</code>
       */
      public com.google.protobuf.ByteString
          getGateBytes() {
        java.lang.Object ref = gate_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          gate_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string gate = 3;</code>
       */
      public Builder setGate(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        gate_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string gate = 3;</code>
       */
      public Builder clearGate() {
        
        gate_ = getDefaultInstance().getGate();
        onChanged();
        return this;
      }
      /**
       * <code>string gate = 3;</code>
       */
      public Builder setGateBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        gate_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object game_ = "";
      /**
       * <code>string game = 4;</code>
       */
      public java.lang.String getGame() {
        java.lang.Object ref = game_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          game_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string game = 4;</code>
       */
      public com.google.protobuf.ByteString
          getGameBytes() {
        java.lang.Object ref = game_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          game_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string game = 4;</code>
       */
      public Builder setGame(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        game_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string game = 4;</code>
       */
      public Builder clearGame() {
        
        game_ = getDefaultInstance().getGame();
        onChanged();
        return this;
      }
      /**
       * <code>string game = 4;</code>
       */
      public Builder setGameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        game_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:GTB_REGIST_ONLINE)
    }

    // @@protoc_insertion_point(class_scope:GTB_REGIST_ONLINE)
    private static final com.net.msg.BUS_MSG.GTB_REGIST_ONLINE DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.net.msg.BUS_MSG.GTB_REGIST_ONLINE();
    }

    public static com.net.msg.BUS_MSG.GTB_REGIST_ONLINE getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<GTB_REGIST_ONLINE>
        PARSER = new com.google.protobuf.AbstractParser<GTB_REGIST_ONLINE>() {
      @java.lang.Override
      public GTB_REGIST_ONLINE parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new GTB_REGIST_ONLINE(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<GTB_REGIST_ONLINE> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<GTB_REGIST_ONLINE> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.net.msg.BUS_MSG.GTB_REGIST_ONLINE getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface GTB_OFFLINEOrBuilder extends
      // @@protoc_insertion_point(interface_extends:GTB_OFFLINE)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int64 uid = 1;</code>
     */
    long getUid();
  }
  /**
   * Protobuf type {@code GTB_OFFLINE}
   */
  public  static final class GTB_OFFLINE extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:GTB_OFFLINE)
      GTB_OFFLINEOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use GTB_OFFLINE.newBuilder() to construct.
    private GTB_OFFLINE(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private GTB_OFFLINE() {
      uid_ = 0L;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private GTB_OFFLINE(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              uid_ = input.readInt64();
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.net.msg.BUS_MSG.internal_static_GTB_OFFLINE_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.net.msg.BUS_MSG.internal_static_GTB_OFFLINE_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.net.msg.BUS_MSG.GTB_OFFLINE.class, com.net.msg.BUS_MSG.GTB_OFFLINE.Builder.class);
    }

    public static final int UID_FIELD_NUMBER = 1;
    private long uid_;
    /**
     * <code>int64 uid = 1;</code>
     */
    public long getUid() {
      return uid_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (uid_ != 0L) {
        output.writeInt64(1, uid_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (uid_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, uid_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.net.msg.BUS_MSG.GTB_OFFLINE)) {
        return super.equals(obj);
      }
      com.net.msg.BUS_MSG.GTB_OFFLINE other = (com.net.msg.BUS_MSG.GTB_OFFLINE) obj;

      boolean result = true;
      result = result && (getUid()
          == other.getUid());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + UID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getUid());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.net.msg.BUS_MSG.GTB_OFFLINE parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.net.msg.BUS_MSG.GTB_OFFLINE parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.net.msg.BUS_MSG.GTB_OFFLINE parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.net.msg.BUS_MSG.GTB_OFFLINE parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.net.msg.BUS_MSG.GTB_OFFLINE parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.net.msg.BUS_MSG.GTB_OFFLINE parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.net.msg.BUS_MSG.GTB_OFFLINE parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.net.msg.BUS_MSG.GTB_OFFLINE parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.net.msg.BUS_MSG.GTB_OFFLINE parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.net.msg.BUS_MSG.GTB_OFFLINE parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.net.msg.BUS_MSG.GTB_OFFLINE parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.net.msg.BUS_MSG.GTB_OFFLINE parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.net.msg.BUS_MSG.GTB_OFFLINE prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code GTB_OFFLINE}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:GTB_OFFLINE)
        com.net.msg.BUS_MSG.GTB_OFFLINEOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.net.msg.BUS_MSG.internal_static_GTB_OFFLINE_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.net.msg.BUS_MSG.internal_static_GTB_OFFLINE_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.net.msg.BUS_MSG.GTB_OFFLINE.class, com.net.msg.BUS_MSG.GTB_OFFLINE.Builder.class);
      }

      // Construct using com.net.msg.BUS_MSG.GTB_OFFLINE.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        uid_ = 0L;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.net.msg.BUS_MSG.internal_static_GTB_OFFLINE_descriptor;
      }

      @java.lang.Override
      public com.net.msg.BUS_MSG.GTB_OFFLINE getDefaultInstanceForType() {
        return com.net.msg.BUS_MSG.GTB_OFFLINE.getDefaultInstance();
      }

      @java.lang.Override
      public com.net.msg.BUS_MSG.GTB_OFFLINE build() {
        com.net.msg.BUS_MSG.GTB_OFFLINE result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.net.msg.BUS_MSG.GTB_OFFLINE buildPartial() {
        com.net.msg.BUS_MSG.GTB_OFFLINE result = new com.net.msg.BUS_MSG.GTB_OFFLINE(this);
        result.uid_ = uid_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.net.msg.BUS_MSG.GTB_OFFLINE) {
          return mergeFrom((com.net.msg.BUS_MSG.GTB_OFFLINE)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.net.msg.BUS_MSG.GTB_OFFLINE other) {
        if (other == com.net.msg.BUS_MSG.GTB_OFFLINE.getDefaultInstance()) return this;
        if (other.getUid() != 0L) {
          setUid(other.getUid());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.net.msg.BUS_MSG.GTB_OFFLINE parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.net.msg.BUS_MSG.GTB_OFFLINE) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long uid_ ;
      /**
       * <code>int64 uid = 1;</code>
       */
      public long getUid() {
        return uid_;
      }
      /**
       * <code>int64 uid = 1;</code>
       */
      public Builder setUid(long value) {
        
        uid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 uid = 1;</code>
       */
      public Builder clearUid() {
        
        uid_ = 0L;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:GTB_OFFLINE)
    }

    // @@protoc_insertion_point(class_scope:GTB_OFFLINE)
    private static final com.net.msg.BUS_MSG.GTB_OFFLINE DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.net.msg.BUS_MSG.GTB_OFFLINE();
    }

    public static com.net.msg.BUS_MSG.GTB_OFFLINE getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<GTB_OFFLINE>
        PARSER = new com.google.protobuf.AbstractParser<GTB_OFFLINE>() {
      @java.lang.Override
      public GTB_OFFLINE parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new GTB_OFFLINE(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<GTB_OFFLINE> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<GTB_OFFLINE> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.net.msg.BUS_MSG.GTB_OFFLINE getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface GTB_ONLINE_UIDS_HEARTOrBuilder extends
      // @@protoc_insertion_point(interface_extends:GTB_ONLINE_UIDS_HEART)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated int64 uids = 1;</code>
     */
    java.util.List<java.lang.Long> getUidsList();
    /**
     * <code>repeated int64 uids = 1;</code>
     */
    int getUidsCount();
    /**
     * <code>repeated int64 uids = 1;</code>
     */
    long getUids(int index);
  }
  /**
   * Protobuf type {@code GTB_ONLINE_UIDS_HEART}
   */
  public  static final class GTB_ONLINE_UIDS_HEART extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:GTB_ONLINE_UIDS_HEART)
      GTB_ONLINE_UIDS_HEARTOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use GTB_ONLINE_UIDS_HEART.newBuilder() to construct.
    private GTB_ONLINE_UIDS_HEART(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private GTB_ONLINE_UIDS_HEART() {
      uids_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private GTB_ONLINE_UIDS_HEART(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                uids_ = new java.util.ArrayList<java.lang.Long>();
                mutable_bitField0_ |= 0x00000001;
              }
              uids_.add(input.readInt64());
              break;
            }
            case 10: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001) && input.getBytesUntilLimit() > 0) {
                uids_ = new java.util.ArrayList<java.lang.Long>();
                mutable_bitField0_ |= 0x00000001;
              }
              while (input.getBytesUntilLimit() > 0) {
                uids_.add(input.readInt64());
              }
              input.popLimit(limit);
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          uids_ = java.util.Collections.unmodifiableList(uids_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.net.msg.BUS_MSG.internal_static_GTB_ONLINE_UIDS_HEART_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.net.msg.BUS_MSG.internal_static_GTB_ONLINE_UIDS_HEART_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.net.msg.BUS_MSG.GTB_ONLINE_UIDS_HEART.class, com.net.msg.BUS_MSG.GTB_ONLINE_UIDS_HEART.Builder.class);
    }

    public static final int UIDS_FIELD_NUMBER = 1;
    private java.util.List<java.lang.Long> uids_;
    /**
     * <code>repeated int64 uids = 1;</code>
     */
    public java.util.List<java.lang.Long>
        getUidsList() {
      return uids_;
    }
    /**
     * <code>repeated int64 uids = 1;</code>
     */
    public int getUidsCount() {
      return uids_.size();
    }
    /**
     * <code>repeated int64 uids = 1;</code>
     */
    public long getUids(int index) {
      return uids_.get(index);
    }
    private int uidsMemoizedSerializedSize = -1;

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (getUidsList().size() > 0) {
        output.writeUInt32NoTag(10);
        output.writeUInt32NoTag(uidsMemoizedSerializedSize);
      }
      for (int i = 0; i < uids_.size(); i++) {
        output.writeInt64NoTag(uids_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      {
        int dataSize = 0;
        for (int i = 0; i < uids_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeInt64SizeNoTag(uids_.get(i));
        }
        size += dataSize;
        if (!getUidsList().isEmpty()) {
          size += 1;
          size += com.google.protobuf.CodedOutputStream
              .computeInt32SizeNoTag(dataSize);
        }
        uidsMemoizedSerializedSize = dataSize;
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.net.msg.BUS_MSG.GTB_ONLINE_UIDS_HEART)) {
        return super.equals(obj);
      }
      com.net.msg.BUS_MSG.GTB_ONLINE_UIDS_HEART other = (com.net.msg.BUS_MSG.GTB_ONLINE_UIDS_HEART) obj;

      boolean result = true;
      result = result && getUidsList()
          .equals(other.getUidsList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getUidsCount() > 0) {
        hash = (37 * hash) + UIDS_FIELD_NUMBER;
        hash = (53 * hash) + getUidsList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.net.msg.BUS_MSG.GTB_ONLINE_UIDS_HEART parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.net.msg.BUS_MSG.GTB_ONLINE_UIDS_HEART parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.net.msg.BUS_MSG.GTB_ONLINE_UIDS_HEART parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.net.msg.BUS_MSG.GTB_ONLINE_UIDS_HEART parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.net.msg.BUS_MSG.GTB_ONLINE_UIDS_HEART parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.net.msg.BUS_MSG.GTB_ONLINE_UIDS_HEART parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.net.msg.BUS_MSG.GTB_ONLINE_UIDS_HEART parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.net.msg.BUS_MSG.GTB_ONLINE_UIDS_HEART parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.net.msg.BUS_MSG.GTB_ONLINE_UIDS_HEART parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.net.msg.BUS_MSG.GTB_ONLINE_UIDS_HEART parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.net.msg.BUS_MSG.GTB_ONLINE_UIDS_HEART parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.net.msg.BUS_MSG.GTB_ONLINE_UIDS_HEART parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.net.msg.BUS_MSG.GTB_ONLINE_UIDS_HEART prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code GTB_ONLINE_UIDS_HEART}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:GTB_ONLINE_UIDS_HEART)
        com.net.msg.BUS_MSG.GTB_ONLINE_UIDS_HEARTOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.net.msg.BUS_MSG.internal_static_GTB_ONLINE_UIDS_HEART_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.net.msg.BUS_MSG.internal_static_GTB_ONLINE_UIDS_HEART_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.net.msg.BUS_MSG.GTB_ONLINE_UIDS_HEART.class, com.net.msg.BUS_MSG.GTB_ONLINE_UIDS_HEART.Builder.class);
      }

      // Construct using com.net.msg.BUS_MSG.GTB_ONLINE_UIDS_HEART.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        uids_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.net.msg.BUS_MSG.internal_static_GTB_ONLINE_UIDS_HEART_descriptor;
      }

      @java.lang.Override
      public com.net.msg.BUS_MSG.GTB_ONLINE_UIDS_HEART getDefaultInstanceForType() {
        return com.net.msg.BUS_MSG.GTB_ONLINE_UIDS_HEART.getDefaultInstance();
      }

      @java.lang.Override
      public com.net.msg.BUS_MSG.GTB_ONLINE_UIDS_HEART build() {
        com.net.msg.BUS_MSG.GTB_ONLINE_UIDS_HEART result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.net.msg.BUS_MSG.GTB_ONLINE_UIDS_HEART buildPartial() {
        com.net.msg.BUS_MSG.GTB_ONLINE_UIDS_HEART result = new com.net.msg.BUS_MSG.GTB_ONLINE_UIDS_HEART(this);
        int from_bitField0_ = bitField0_;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          uids_ = java.util.Collections.unmodifiableList(uids_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.uids_ = uids_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.net.msg.BUS_MSG.GTB_ONLINE_UIDS_HEART) {
          return mergeFrom((com.net.msg.BUS_MSG.GTB_ONLINE_UIDS_HEART)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.net.msg.BUS_MSG.GTB_ONLINE_UIDS_HEART other) {
        if (other == com.net.msg.BUS_MSG.GTB_ONLINE_UIDS_HEART.getDefaultInstance()) return this;
        if (!other.uids_.isEmpty()) {
          if (uids_.isEmpty()) {
            uids_ = other.uids_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureUidsIsMutable();
            uids_.addAll(other.uids_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.net.msg.BUS_MSG.GTB_ONLINE_UIDS_HEART parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.net.msg.BUS_MSG.GTB_ONLINE_UIDS_HEART) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<java.lang.Long> uids_ = java.util.Collections.emptyList();
      private void ensureUidsIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          uids_ = new java.util.ArrayList<java.lang.Long>(uids_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <code>repeated int64 uids = 1;</code>
       */
      public java.util.List<java.lang.Long>
          getUidsList() {
        return java.util.Collections.unmodifiableList(uids_);
      }
      /**
       * <code>repeated int64 uids = 1;</code>
       */
      public int getUidsCount() {
        return uids_.size();
      }
      /**
       * <code>repeated int64 uids = 1;</code>
       */
      public long getUids(int index) {
        return uids_.get(index);
      }
      /**
       * <code>repeated int64 uids = 1;</code>
       */
      public Builder setUids(
          int index, long value) {
        ensureUidsIsMutable();
        uids_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int64 uids = 1;</code>
       */
      public Builder addUids(long value) {
        ensureUidsIsMutable();
        uids_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int64 uids = 1;</code>
       */
      public Builder addAllUids(
          java.lang.Iterable<? extends java.lang.Long> values) {
        ensureUidsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, uids_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int64 uids = 1;</code>
       */
      public Builder clearUids() {
        uids_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:GTB_ONLINE_UIDS_HEART)
    }

    // @@protoc_insertion_point(class_scope:GTB_ONLINE_UIDS_HEART)
    private static final com.net.msg.BUS_MSG.GTB_ONLINE_UIDS_HEART DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.net.msg.BUS_MSG.GTB_ONLINE_UIDS_HEART();
    }

    public static com.net.msg.BUS_MSG.GTB_ONLINE_UIDS_HEART getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<GTB_ONLINE_UIDS_HEART>
        PARSER = new com.google.protobuf.AbstractParser<GTB_ONLINE_UIDS_HEART>() {
      @java.lang.Override
      public GTB_ONLINE_UIDS_HEART parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new GTB_ONLINE_UIDS_HEART(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<GTB_ONLINE_UIDS_HEART> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<GTB_ONLINE_UIDS_HEART> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.net.msg.BUS_MSG.GTB_ONLINE_UIDS_HEART getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GTB_REGIST_ONLINE_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GTB_REGIST_ONLINE_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GTB_OFFLINE_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GTB_OFFLINE_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GTB_ONLINE_UIDS_HEART_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GTB_ONLINE_UIDS_HEART_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\tbus.proto\032\roptions.proto\"V\n\021GTB_REGIST" +
      "_ONLINE\022\013\n\003uid\030\001 \001(\003\022\020\n\010playerId\030\002 \001(\003\022\014" +
      "\n\004gate\030\003 \001(\t\022\014\n\004game\030\004 \001(\t:\006\230\202\031\321\206\003\"\"\n\013GT" +
      "B_OFFLINE\022\013\n\003uid\030\001 \001(\003:\006\230\202\031\322\206\003\"-\n\025GTB_ON" +
      "LINE_UIDS_HEART\022\014\n\004uids\030\001 \003(\003:\006\230\202\031\323\206\003B\026\n" +
      "\013com.net.msgB\007BUS_MSGb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.net.msg.Options.getDescriptor(),
        }, assigner);
    internal_static_GTB_REGIST_ONLINE_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_GTB_REGIST_ONLINE_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GTB_REGIST_ONLINE_descriptor,
        new java.lang.String[] { "Uid", "PlayerId", "Gate", "Game", });
    internal_static_GTB_OFFLINE_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_GTB_OFFLINE_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GTB_OFFLINE_descriptor,
        new java.lang.String[] { "Uid", });
    internal_static_GTB_ONLINE_UIDS_HEART_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_GTB_ONLINE_UIDS_HEART_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GTB_ONLINE_UIDS_HEART_descriptor,
        new java.lang.String[] { "Uids", });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(com.net.msg.Options.messageId);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
    com.net.msg.Options.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
